# Generated by Django 4.2.7 on 2025-08-09 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='場所名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='定員')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '場所',
                'verbose_name_plural': '場所',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '時間枠',
                'verbose_name_plural': '時間枠',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='予約日')),
                ('customer_name', models.CharField(max_length=100, verbose_name='お客様名')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('customer_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は数字、ハイフン、括弧、スペースのみ使用可能です', regex='^[\\d\\-\\(\\)\\s]+$')], verbose_name='電話番号')),
                ('status', models.CharField(choices=[('confirmed', '確認済み'), ('pending', '保留中'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location', verbose_name='場所')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.timeslot', verbose_name='時間枠')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-date', 'time_slot__start_time'],
                'unique_together': {('location', 'time_slot', 'date')},
            },
        ),
    ]
