# Generated by Django 4.2.7 on 2025-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': '場所', 'verbose_name_plural': '場所'},
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='定員'),
        ),
    ]
