# Generated by Django 4.2.7 on 2026-01-12 00:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_add_timeslot_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プラン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='価格')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルトプラン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会員プラン',
                'verbose_name_plural': '会員プラン',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は数字、ハイフン、括弧、スペースのみ使用可能です', regex='^[\\d\\-\\(\\)\\s]+$')], verbose_name='電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=reservations.models.member_photo_upload_path, verbose_name='顔写真')),
                ('card_number_encrypted', models.CharField(blank=True, max_length=255, verbose_name='カード番号（暗号化）')),
                ('card_expiry_month', models.IntegerField(blank=True, null=True, verbose_name='カード有効期限（月）')),
                ('card_expiry_year', models.IntegerField(blank=True, null=True, verbose_name='カード有効期限（年）')),
                ('card_cvc_encrypted', models.CharField(blank=True, max_length=255, verbose_name='CVC（暗号化）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.plan', verbose_name='プラン')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '会員プロフィール',
                'verbose_name_plural': '会員プロフィール',
            },
        ),
    ]
