# Generated by Django 4.2.7 on 2026-01-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_plan_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Square決済ID')),
                ('square_order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Square注文ID')),
                ('payment_link_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='決済リンクID')),
                ('payment_link_url', models.URLField(blank=True, null=True, verbose_name='決済リンクURL')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('status', models.CharField(choices=[('pending', '保留中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.memberprofile', verbose_name='会員')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '決済トランザクション',
                'verbose_name_plural': '決済トランザクション',
                'ordering': ['-created_at'],
            },
        ),
    ]
