# Generated by Django 4.2.7 on 2026-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='price_per_30min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='30分あたりの金額（円）'),
        ),
    ]
