# Generated by Django 4.2.7 on 2026-01-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_location_price_per_30min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='birth_date',
        ),
    ]
