# Generated by Django 4.2.7 on 2026-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_special_user',
            field=models.BooleanField(default=False, verbose_name='特別ユーザー'),
        ),
    ]
