# Generated by Django 4.2.7 on 2026-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_memberprofile_member_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='利用日')),
                ('entry_at', models.DateTimeField(verbose_name='入場日時')),
                ('exit_at', models.DateTimeField(blank=True, null=True, verbose_name='退場日時')),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='請求額（円）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location', verbose_name='場所')),
                ('member_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='reservations.memberprofile', verbose_name='会員')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation', verbose_name='紐付け予約')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.timeslot', verbose_name='時間枠')),
            ],
            options={
                'verbose_name': '入退室記録',
                'verbose_name_plural': '入退室記録',
                'ordering': ['-entry_at'],
                'indexes': [models.Index(fields=['date', 'location'], name='reservation_date_fc7aff_idx'), models.Index(fields=['member_profile', 'exit_at'], name='reservation_member__71ecc9_idx')],
            },
        ),
    ]
