"""
Django settings for reservation_system project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-mtim@1y@$*^jyt9+re8p8k-&9njo2f4)v0fxd!l!@%y$pja9e-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# 本番ドメインは環境変数 ALLOWED_HOSTS（カンマ区切り）で上書き可能
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,yomohirokan.com,www.yomohirokan.com',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

# HTTPS 経由のフォーム POST 等（Django 4.0+）。環境変数 CSRF_TRUSTED_ORIGINS で上書き可能
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://yomohirokan.com,https://www.yomohirokan.com',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.line',
    'reservations',
]

SITE_ID = 1

MIDDLEWARE = [
    'reservation_system.security_middleware.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 静的ファイル配信用
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'reservations.middleware.SuperuserRequiredMiddleware',  # スーパーユーザー制限ミドルウェア
]

ROOT_URLCONF = 'reservation_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reservations.context_processors.line_login',
            ],
        },
    },
]

WSGI_APPLICATION = 'reservation_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 環境変数DATABASE_URLが設定されている場合はPostgreSQLを使用
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # PostgreSQLを使用（Docker環境など）
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # SQLiteを使用（ローカル開発環境）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# @login_required 等のログインへリダイレクト先（allauth 既定の /accounts/login/ ではなく自前ログインへ）
LOGIN_URL = '/login/'

# allauth が LINE 等の OAuth で送る redirect_uri のスキーム。
# 既定が http のとき Gunicorn 直(HTTP) では request が http になり、LINE に https だけ登録していると
# 「Invalid redirect_uri」になる。.env で明示するか本番は DEBUG=False にする。
ACCOUNT_DEFAULT_HTTP_PROTOCOL = config(
    'ACCOUNT_DEFAULT_HTTP_PROTOCOL',
    default='https' if not DEBUG else 'http',
).lower()

# LINE 認可へそのまま飛ばす（既定 False だと「続ける」中間ページになる）
SOCIALACCOUNT_LOGIN_ON_GET = True

# LINE Login（LINE Developers の LINE Login チャネルの Channel ID / Secret）
LINE_CHANNEL_ID = config('LINE_CHANNEL_ID', default='')
LINE_CHANNEL_SECRET = config('LINE_CHANNEL_SECRET', default='')
# カンマ区切り。email は OpenID Connect でメール取得の申請承認後のみ有効（未承認だと別エラーになり得る）
# 例: LINE_LOGIN_SCOPE=profile,openid
LINE_LOGIN_SCOPE = [
    s.strip()
    for s in config('LINE_LOGIN_SCOPE', default='profile,openid,email').split(',')
    if s.strip()
]

SOCIALACCOUNT_PROVIDERS = {
    'line': {
        'APP': {
            'client_id': LINE_CHANNEL_ID,
            'secret': LINE_CHANNEL_SECRET,
        },
        'SCOPE': LINE_LOGIN_SCOPE,
    },
}

SOCIALACCOUNT_ADAPTER = 'reservations.adapters.MemberSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_STORE_TOKENS = False

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Security settings for production
if not DEBUG:
    # Nginx + Cloudflare 等: オリジンは HTTP でも来訪は HTTPS のことがある
    # （X-Forwarded-Proto を nginx が Gunicorn に渡す前提。8000 はローカルのみ）
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    # 静的 IP 直では証明書が無いため HTTP のまま許可（ドメイン + Let's Encrypt 後は https のみで十分）
    SECURE_SSL_REDIRECT_EXEMPT_HOSTS = config(
        'SECURE_SSL_REDIRECT_EXEMPT_HOSTS',
        default='54.178.68.240,127.0.0.1,localhost',
        cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
    )
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # 開発環境での警告を抑制
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    SECURE_SSL_REDIRECT_EXEMPT_HOSTS = ()

# Email settings
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='noreply@example.com')

# Square API settings（SQUARE_INTEGRATION_ENABLED=False のときは API を呼ばず、有料も未決済のまま確定扱い）
SQUARE_INTEGRATION_ENABLED = config('SQUARE_INTEGRATION_ENABLED', default=False, cast=bool)
SQUARE_APPLICATION_ID = config('SQUARE_APPLICATION_ID', default='sandbox-sq0idb-Klqy4yYEmO_5_1Ea9msc3w')
SQUARE_ACCESS_TOKEN = config('SQUARE_ACCESS_TOKEN', default='EAAAl5UHQGekKNOWGRkLWMJ7NTohmkFaFRZXL2wioazmvTMi-PcFmU9SHpwwdSSe')
SQUARE_ENVIRONMENT = config('SQUARE_ENVIRONMENT', default='sandbox')  # sandbox or production
SQUARE_LOCATION_ID = config('SQUARE_LOCATION_ID', default='LHQHHBA22J5E1')
