from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'reservations'

urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.location_list, name='location_list'),
    path('reservations/', views.reservation_list, name='reservation_list'),
    path('my-reservations/', views.my_reservations, name='my_reservations'),
    path('reservations/create/', views.reservation_create, name='reservation_create'),
    path('reservations/confirm/', views.reservation_confirm, name='reservation_confirm'),
    path('reservations/confirm/submit/', views.reservation_confirm_submit, name='reservation_confirm_submit'),
    path('reservations/<int:pk>/', views.reservation_detail, name='reservation_detail'),
    path('reservations/<int:pk>/edit/', views.reservation_edit, name='reservation_edit'),
    path('reservations/<int:pk>/delete/', views.reservation_delete, name='reservation_delete'),
    path('check-availability/', views.check_availability, name='check_availability'),
    path('reservations/weekly-calendar/', views.reservation_weekly_calendar, name='reservation_weekly_calendar'),
    path('check-weekly-availability/', views.check_weekly_availability, name='check_weekly_availability'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('location-management/', views.location_management, name='location_management'),
    path('location-management/add/', views.location_add, name='location_add'),
    path('locations/<int:pk>/edit/', views.location_edit, name='location_edit'),
    path('locations/<int:pk>/delete/', views.location_delete, name='location_delete'),
    path('time-slot-management/', views.time_slot_management, name='time_slot_management'),
    path('time-slot-management/add/', views.time_slot_add, name='time_slot_add'),
    path('time-slots/<int:pk>/edit/', views.time_slot_edit, name='time_slot_edit'),
    path('time-slots/<int:pk>/delete/', views.time_slot_delete, name='time_slot_delete'),
    path('plan-management/', views.plan_management, name='plan_management'),
    path('plan-management/add/', views.plan_add, name='plan_add'),
    path('plans/<int:pk>/edit/', views.plan_edit, name='plan_edit'),
    path('plans/<int:pk>/delete/', views.plan_delete, name='plan_delete'),
    path('user-management/', views.user_management, name='user_management'),
    path('users/<int:pk>/', views.user_detail, name='user_detail'),
    path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('login/', views.custom_login, name='custom_login'),
    path('logout/', LogoutView.as_view(next_page='reservations:index'), name='logout'),
    path('api/calendar/events/', views.get_calendar_events, name='calendar_events'),
    path('member-registration/', views.member_registration, name='member_registration'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('payment/create/', views.payment_create, name='payment_create'),
    path('payment/create/<int:reservation_id>/', views.payment_create, name='payment_create_reservation'),
    path('payment/complete/', views.payment_complete, name='payment_complete'),
    path('webhooks/square/', views.square_webhook, name='square_webhook'),
]
